# Generated by Django 5.2.5 on 2025-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurakshopprojekt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
    ]
