# Generated by Django 5.2.5 on 2025-09-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurakshopprojekt', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукциялар'},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Барбы?'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='kurakshopprojekt.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_original',
            field=models.BooleanField(default=True, verbose_name='Оригиналбы?'),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон номер'),
        ),
    ]
